import { Router } from 'express';
import { getDb } from '../db/database.js';

export const cityRoutes = Router();

// Default Chinese cities
const DEFAULT_CITIES = [
  { code: '010', name: '北京', province: '北京' },
  { code: '021', name: '上海', province: '上海' },
  { code: '020', name: '广州', province: '广东' },
  { code: '0755', name: '深圳', province: '广东' },
  { code: '022', name: '天津', province: '天津' },
  { code: '023', name: '重庆', province: '重庆' },
  { code: '024', name: '沈阳', province: '辽宁' },
  { code: '027', name: '武汉', province: '湖北' },
  { code: '028', name: '成都', province: '四川' },
  { code: '029', name: '西安', province: '陕西' },
  { code: '025', name: '南京', province: '江苏' },
  { code: '0571', name: '杭州', province: '浙江' },
  { code: '0574', name: '宁波', province: '浙江' },
  { code: '0532', name: '青岛', province: '山东' },
  { code: '0531', name: '济南', province: '山东' },
  { code: '0411', name: '大连', province: '辽宁' },
  { code: '0451', name: '哈尔滨', province: '黑龙江' },
  { code: '0431', name: '长春', province: '吉林' },
  { code: '0771', name: '南宁', province: '广西' },
  { code: '0772', name: '柳州', province: '广西' },
  { code: '0751', name: '韶关', province: '广东' },
  { code: '0752', name: '惠州', province: '广东' },
  { code: '0753', name: '梅州', province: '广东' },
  { code: '0754', name: '汕头', province: '广东' },
  { code: '0756', name: '珠海', province: '广东' },
  { code: '0757', name: '佛山', province: '广东' },
  { code: '0758', name: '肇庆', province: '广东' },
  { code: '0759', name: '湛江', province: '广东' },
  { code: '0760', name: '中山', province: '广东' },
  { code: '0762', name: '河源', province: '广东' },
  { code: '0763', name: '清远', province: '广东' },
  { code: '0766', name: '云浮', province: '广东' },
  { code: '0660', name: '汕尾', province: '广东' },
  { code: '0662', name: '阳江', province: '广东' },
  { code: '0663', name: '揭阳', province: '广东' },
  { code: '0668', name: '茂名', province: '广东' },
  { code: '0691', name: '普洱', province: '云南' },
  { code: '0692', name: '丽江', province: '云南' },
  { code: '0551', name: '合肥', province: '安徽' },
  { code: '0552', name: '蚌埠', province: '安徽' },
  { code: '0553', name: '芜湖', province: '安徽' },
  { code: '0554', name: '淮南', province: '安徽' },
  { code: '0555', name: '马鞍山', province: '安徽' },
  { code: '0556', name: '安庆', province: '安徽' },
  { code: '0557', name: '宿州', province: '安徽' },
  { code: '0558', name: '阜阳', province: '安徽' },
  { code: '0559', name: '黄山', province: '安徽' },
  { code: '0561', name: '淮北', province: '安徽' },
  { code: '0562', name: '铜陵', province: '安徽' },
  { code: '0563', name: '宣城', province: '安徽' },
  { code: '0564', name: '池州', province: '安徽' },
  { code: '0565', name: '滁州', province: '安徽' },
  { code: '0566', name: '六安', province: '安徽' },
  { code: '0574', name: '宁波', province: '浙江' },
  { code: '0575', name: '绍兴', province: '浙江' },
  { code: '0576', name: '温州', province: '浙江' },
  { code: '0577', name: '嘉兴', province: '浙江' },
  { code: '0578', name: '湖州', province: '浙江' },
  { code: '0579', name: '金华', province: '浙江' },
  { code: '0570', name: '衢州', province: '浙江' },
  { code: '0580', name: '舟山', province: '浙江' },
  { code: '0591', name: '福州', province: '福建' },
  { code: '0592', name: '厦门', province: '福建' },
  { code: '0593', name: '宁德', province: '福建' },
  { code: '0594', name: '莆田', province: '福建' },
  { code: '0595', name: '泉州', province: '福建' },
  { code: '0596', name: '漳州', province: '福建' },
  { code: '0597', name: '龙岩', province: '福建' },
  { code: '0598', name: '三明', province: '福建' },
  { code: '0599', name: '南平', province: '福建' },
  { code: '0791', name: '南昌', province: '江西' },
  { code: '0792', name: '九江', province: '江西' },
  { code: '0793', name: '景德镇', province: '江西' },
  { code: '0794', name: '赣州', province: '江西' },
  { code: '0795', name: '宜春', province: '江西' },
  { code: '0796', name: '吉安', province: '江西' },
  { code: '0797', name: '抚州', province: '江西' },
  { code: '0798', name: '上饶', province: '江西' },
  { code: '0799', name: '萍乡', province: '江西' },
  { code: '0790', name: '新余', province: '江西' },
  { code: '0511', name: '镇江', province: '江苏' },
  { code: '0512', name: '苏州', province: '江苏' },
  { code: '0513', name: '南通', province: '江苏' },
  { code: '0514', name: '扬州', province: '江苏' },
  { code: '0515', name: '盐城', province: '江苏' },
  { code: '0516', name: '徐州', province: '江苏' },
  { code: '0517', name: '淮安', province: '江苏' },
  { code: '0518', name: '连云港', province: '江苏' },
  { code: '0519', name: '常州', province: '江苏' },
  { code: '0523', name: '泰州', province: '江苏' },
  { code: '0524', name: '宿迁', province: '江苏' },
  { code: '0531', name: '济南', province: '山东' },
  { code: '0532', name: '青岛', province: '山东' },
  { code: '0533', name: '淄博', province: '山东' },
  { code: '0534', name: '德州', province: '山东' },
  { code: '0535', name: '烟台', province: '山东' },
  { code: '0536', name: '潍坊', province: '山东' },
  { code: '0537', name: '济宁', province: '山东' },
  { code: '0538', name: '泰安', province: '山东' },
  { code: '0539', name: '临沂', province: '山东' },
  { code: '0543', name: '滨州', province: '山东' },
  { code: '0546', name: '东营', province: '山东' },
  { code: '0631', name: '威海', province: '山东' },
  { code: '0632', name: '枣庄', province: '山东' },
  { code: '0633', name: '日照', province: '山东' },
  { code: '0635', name: '聊城', province: '山东' },
  { code: '0371', name: '郑州', province: '河南' },
  { code: '0372', name: '安阳', province: '河南' },
  { code: '0373', name: '新乡', province: '河南' },
  { code: '0374', name: '许昌', province: '河南' },
  { code: '0375', name: '平顶山', province: '河南' },
  { code: '0376', name: '信阳', province: '河南' },
  { code: '0377', name: '南阳', province: '河南' },
  { code: '0378', name: '开封', province: '河南' },
  { code: '0379', name: '洛阳', province: '河南' },
  { code: '0370', name: '商丘', province: '河南' },
  { code: '0391', name: '焦作', province: '河南' },
  { code: '0392', name: '鹤壁', province: '河南' },
  { code: '0393', name: '濮阳', province: '河南' },
  { code: '0394', name: '周口', province: '河南' },
  { code: '0395', name: '漯河', province: '河南' },
  { code: '0396', name: '驻马店', province: '河南' },
  { code: '0398', name: '三门峡', province: '河南' },
  { code: '0379', name: '洛阳', province: '河南' },
  { code: '027', name: '武汉', province: '湖北' },
  { code: '0714', name: '黄石', province: '湖北' },
  { code: '0715', name: '咸宁', province: '湖北' },
  { code: '0716', name: '荆州', province: '湖北' },
  { code: '0717', name: '宜昌', province: '湖北' },
  { code: '0718', name: '恩施', province: '湖北' },
  { code: '0719', name: '十堰', province: '湖北' },
  { code: '0722', name: '随州', province: '湖北' },
  { code: '0724', name: '荆门', province: '湖北' },
  { code: '0710', name: '襄阳', province: '湖北' },
  { code: '0711', name: '鄂州', province: '湖北' },
  { code: '0713', name: '黄冈', province: '湖北' },
  { code: '0731', name: '长沙', province: '湖南' },
  { code: '0730', name: '岳阳', province: '湖南' },
  { code: '0732', name: '湘潭', province: '湖南' },
  { code: '0733', name: '株洲', province: '湖南' },
  { code: '0734', name: '衡阳', province: '湖南' },
  { code: '0735', name: '郴州', province: '湖南' },
  { code: '0736', name: '常德', province: '湖南' },
  { code: '0737', name: '益阳', province: '湖南' },
  { code: '0738', name: '娄底', province: '湖南' },
  { code: '0739', name: '邵阳', province: '湖南' },
  { code: '0743', name: '吉首', province: '湖南' },
  { code: '0744', name: '张家界', province: '湖南' },
  { code: '0745', name: '怀化', province: '湖南' },
  { code: '0746', name: '永州', province: '湖南' },
  { code: '020', name: '广州', province: '广东' },
  { code: '021', name: '上海', province: '上海' },
  { code: '010', name: '北京', province: '北京' },
  { code: '023', name: '重庆', province: '重庆' },
  { code: '022', name: '天津', province: '天津' },
  { code: '024', name: '沈阳', province: '辽宁' },
  { code: '028', name: '成都', province: '四川' },
  { code: '029', name: '西安', province: '陕西' },
  { code: '025', name: '南京', province: '江苏' },
  { code: '0571', name: '杭州', province: '浙江' },
  { code: '0871', name: '昆明', province: '云南' },
  { code: '0872', name: '大理', province: '云南' },
  { code: '0873', name: '红河', province: '云南' },
  { code: '0874', name: '曲靖', province: '云南' },
  { code: '0875', name: '保山', province: '云南' },
  { code: '0877', name: '玉溪', province: '云南' },
  { code: '0878', name: '楚雄', province: '云南' },
  { code: '0879', name: '普洱', province: '云南' },
  { code: '0883', name: '临沧', province: '云南' },
  { code: '0886', name: '怒江', province: '云南' },
  { code: '0887', name: '迪庆', province: '云南' },
  { code: '0888', name: '丽江', province: '云南' },
  { code: '0891', name: '拉萨', province: '西藏' },
  { code: '0892', name: '日喀则', province: '西藏' },
  { code: '0893', name: '山南', province: '西藏' },
  { code: '0894', name: '林芝', province: '西藏' },
  { code: '0895', name: '昌都', province: '西藏' },
  { code: '0896', name: '那曲', province: '西藏' },
  { code: '0897', name: '阿里', province: '西藏' },
  { code: '0931', name: '兰州', province: '甘肃' },
  { code: '0932', name: '定西', province: '甘肃' },
  { code: '0933', name: '平凉', province: '甘肃' },
  { code: '0934', name: '庆阳', province: '甘肃' },
  { code: '0935', name: '金昌', province: '甘肃' },
  { code: '0936', name: '武威', province: '甘肃' },
  { code: '0937', name: '酒泉', province: '甘肃' },
  { code: '0938', name: '张掖', province: '甘肃' },
  { code: '0939', name: '天水', province: '甘肃' },
  { code: '0941', name: '甘南', province: '甘肃' },
  { code: '0943', name: '临夏', province: '甘肃' },
  { code: '0951', name: '银川', province: '宁夏' },
  { code: '0952', name: '石嘴山', province: '宁夏' },
  { code: '0953', name: '吴忠', province: '宁夏' },
  { code: '0954', name: '固原', province: '宁夏' },
  { code: '0955', name: '中卫', province: '宁夏' },
  { code: '0971', name: '西宁', province: '青海' },
  { code: '0972', name: '海东', province: '青海' },
  { code: '0973', name: '海南', province: '青海' },
  { code: '0974', name: '海西', province: '青海' },
  { code: '0975', name: '玉树', province: '青海' },
  { code: '0976', name: '果洛', province: '青海' },
  { code: '0977', name: '海北', province: '青海' },
  { code: '0991', name: '乌鲁木齐', province: '新疆' },
  { code: '0992', name: '克拉玛依', province: '新疆' },
  { code: '0993', name: '石河子', province: '新疆' },
  { code: '0994', name: '吐鲁番', province: '新疆' },
  { code: '0995', name: '库尔勒', province: '新疆' },
  { code: '0996', name: '喀什', province: '新疆' },
  { code: '0997', name: '阿克苏', province: '新疆' },
  { code: '0998', name: '和田', province: '新疆' },
  { code: '0999', name: '伊宁', province: '新疆' },
  { code: '0471', name: '呼和浩特', province: '内蒙古' },
  { code: '0472', name: '包头', province: '内蒙古' },
  { code: '0473', name: '乌海', province: '内蒙古' },
  { code: '0474', name: '集宁', province: '内蒙古' },
  { code: '0475', name: '通辽', province: '内蒙古' },
  { code: '0476', name: '赤峰', province: '内蒙古' },
  { code: '0477', name: '鄂尔多斯', province: '内蒙古' },
  { code: '0478', name: '巴彦淖尔', province: '内蒙古' },
  { code: '0479', name: '锡林浩特', province: '内蒙古' },
  { code: '0482', name: '乌兰浩特', province: '内蒙古' },
  { code: '0451', name: '哈尔滨', province: '黑龙江' },
  { code: '0452', name: '齐齐哈尔', province: '黑龙江' },
  { code: '0453', name: '牡丹江', province: '黑龙江' },
  { code: '0454', name: '佳木斯', province: '黑龙江' },
  { code: '0455', name: '绥化', province: '黑龙江' },
  { code: '0456', name: '黑河', province: '黑龙江' },
  { code: '0457', name: '大兴安岭', province: '黑龙江' },
  { code: '0458', name: '伊春', province: '黑龙江' },
  { code: '0459', name: '大庆', province: '黑龙江' },
  { code: '0464', name: '鸡西', province: '黑龙江' },
  { code: '0467', name: '双鸭山', province: '黑龙江' },
  { code: '0468', name: '鹤岗', province: '黑龙江' },
  { code: '0431', name: '长春', province: '吉林' },
  { code: '0432', name: '吉林', province: '吉林' },
  { code: '0433', name: '延边', province: '吉林' },
  { code: '0434', name: '四平', province: '吉林' },
  { code: '0435', name: '通化', province: '吉林' },
  { code: '0436', name: '白城', province: '吉林' },
  { code: '0437', name: '辽源', province: '吉林' },
  { code: '0438', name: '松原', province: '吉林' },
  { code: '024', name: '沈阳', province: '辽宁' },
  { code: '0411', name: '大连', province: '辽宁' },
  { code: '0412', name: '鞍山', province: '辽宁' },
  { code: '0413', name: '抚顺', province: '辽宁' },
  { code: '0414', name: '本溪', province: '辽宁' },
  { code: '0415', name: '丹东', province: '辽宁' },
  { code: '0416', name: '锦州', province: '辽宁' },
  { code: '0417', name: '营口', province: '辽宁' },
  { code: '0418', name: '阜新', province: '辽宁' },
  { code: '0419', name: '辽阳', province: '辽宁' },
  { code: '0421', name: '朝阳', province: '辽宁' },
  { code: '0427', name: '盘锦', province: '辽宁' },
  { code: '0429', name: '葫芦岛', province: '辽宁' },
  { code: '024', name: '铁岭', province: '辽宁' },
  { code: '0419', name: '阜新', province: '辽宁' }
];

// Get all cities
cityRoutes.get('/', (req, res) => {
  // Return default cities
  res.json(DEFAULT_CITIES);
});

// Search cities
cityRoutes.get('/search', (req, res) => {
  const query = (req.query.q || '').toLowerCase();
  if (!query) {
    return res.json(DEFAULT_CITIES);
  }

  const results = DEFAULT_CITIES.filter(c =>
    c.name.toLowerCase().includes(query) ||
    c.province.toLowerCase().includes(query)
  );

  res.json(results.slice(0, 20));
});